### ISSUE TITLE
docker-composer up error

### ISSUE THREAD

**Issue by lamjack** [hach-que-docker/phabricator#18]
hi all,

i got a problem.

my docker-composer.yml file,

```yaml
mariadb:
  restart: always
  image: hachque/mariadb
  volumes:
    - /home/docker/srv/phabricator/mariadb:/var/lib/mysql
phabricator:
  restart: always
  image: hachque/phabricator
  volumes:
    - /home/docker/script/phabricator/config:/config
    - /home/docker/srv/phabricator/repo:/srv/repo
  ports:
    - 22:22
    - 22280:22280
  links:
    - mariadb:linked_mariadb
  environment:
    - VIRTUAL_HOST=phabricator.xxx.com
```

and the script.pre file,
```yaml
#!/bin/bash

# Set the name of the host running MySQL:
./bin/config set mysql.host "$LINKED_MARIADB_PORT_3306_TCP_ADDR"

# If MySQL is running on a non-standard port:
./bin/config set mysql.port "$LINKED_MARIADB_PORT_3306_TCP_PORT"

# Set the username for connecting to MySQL:
./bin/config set mysql.user "root"

# Set the password for connecting to MySQL:
./bin/config set mysql.pass ""

# Set the base URI that will be used to access Phabricator:
./bin/config set phabricator.base-uri "https://phabricator.xxx.com/"
```

when i runing the docker-composer up command,

i got the error log,

```bash
phabricator_1 | Raw MySQL Error: Attempt to connect to root@172.17.0.3 failed with error
phabricator_1 | #1130: Host '172.17.0.4' is not allowed to connect to this MariaDB server.
phabricator_1 | [ FAILED ] /etc/init.simple/10-boot-conf
```

could tell me what happen?
