### ISSUE TITLE
Clarification: Setup of SSH repository (git) access

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [hach-que-docker/phabricator#49]
Hi there,

the dockerhub container is promoted with:

> This is a Docker image which provides a fully configured Phabricator image, including SSH connectivity to repositories, real-time notifications via Web Sockets and all of the other parts that are normally difficult to configure done for you.

Additionally i saw this phabricator configuration guide for repository ssh:
https://secure.phabricator.com/book/phabricator/article/diffusion_hosting/#troubleshooting-ssh

No i am confused which part of the configuration guide is already done in the docker container and which not. Some kind of documentation of the last necessary steps would be helpful. After i added the PHABRICATOR_HOST_KEYS_PATH as a mounted volume, i get the following errors:
```

[ STARTING ] /etc/init.simple/45-phabricator-ssh
cp: cannot stat '/hostkeys/*': No such file or directory
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
Waiting for /run/sshd-phabricator.pid to appear...
```

Which keys are expected, how to generate them?

**Comment by hach-que** [comment]
What's the `docker run` command you're using?

**Comment by hach-que** [comment]
Beyond configuring the appropriate volume mounts and environment variables, this Docker image does configure everything you need for SSH:

```
docker run ... \
    --env PHABRICATOR_HOST_KEYS_PATH=/hostkeys/persisted \
    -v /path/on/host:/hostkeys \
    ...
```

Note that you'll probably need to create `/path/on/host` as Docker may no longer create host directories for you.

**Comment by cguentherTUChemnitz** [comment]
I am using the following compose file content:

```
version: '2'

services:
  phabricator:
    build: ./configured-private-phabricator/
    container_name: phabricator
    hostname: phabricator
    volumes:
      - ./phabricator/data/repo:/repos
      - ./phabricator/data/files:/files
      - ./phabricator/hostkeys:/hostkeys
    environment:
      - PHABRICATOR_HOST=phabricator.<MYFQDN>
      - MYSQL_HOST=sqlDB
      - MYSQL_USER=<MYTOTALLYSECURESMYSQLUSER>
      - MYSQL_PASS=<MYTOTALLYSECURESMYSQLPASSWD>
      - PHABRICATOR_REPOSITORY_PATH=/repos
      - PHABRICATOR_STORAGE_TYPE=disk
      - PHABRICATOR_STORAGE_PATH=/files
      - ENABLE_APCU=true
      - ENABLE_UPDATE_ON_START=false
      - SSL_TYPE=external
      - PHABRICATOR_HOST_KEYS_PATH=/hostkeys
    links:
      - mariadb-phabricator:sqlDB
    expose:
      - "80"
      - "22280"
    ports:
      - "22:22"

  mariadb-phabricator:
    image: mariadb:10.1
    hostname: sqlDB
    container_name: mariadb-phabricator
    volumes:
      - ./phabricator/mariadb/data:/var/lib/mysql
      - ./phabricator/mariadb/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=<MYTOTALLYSECURESMYSQLPASSWD>
    expose:
      - "3306"
```
The configured private phabricator image uses your image and adds some private configuration, like phpmailer configs.

The ./phabricator/hostkeys directory exists and is currently empty and (for debug reasons) readable and writable for everyone.
