### ISSUE TITLE
Not able to install with docker 

### ISSUE THREAD

**Issue by bhargavjoshi** [hach-que-docker/phabricator#56]
Sorry I am just getting started to learn docker, 

I am using docker-compose, I don't know what I am doing wrong, here is my docker file.

```
version: '2'
services:
  phabricator:
    restart: always
    ports:
     - "62443:443"
     - "62080:80"
     - "62022:22"
    volumes:
     - /srv/docker/phabricator/repos:/repos
     - /srv/docker/phabricator/extensions:/srv/phabricator/phabricator/src/extensions
     - /srv/docker/phabricator/sshkeys:/sshkeys
     - /srv/docker/phabricator/filestore:/filestore
    depends_on:
     - mysql
    links:
     - mysql
    environment:
     - MYSQL_LINKED_CONTAINER=mysql
     - PHABRICATOR_REPOSITORY_PATH=/repos
     - PHABRICATOR_HOST_KEYS_PATH=/sshkeys
     - PHABRICATOR_HOST=myhost
     - SSL_TYPE=letsencrypt
     - SSL_EMAIL='myemail'
     - PHABRICATOR_STORAGE_TYPE=disk
     - PHABRICATOR_STORAGE_PATH=/filestore
    image: hachque/phabricator
  mysql:
    restart: always
    volumes:
     - /srv/docker/phabricator/mysql:/var/lib/mysql
    image: mysql:5.7.14
    environment:
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
     - MYSQL_USER=phabricator
     - MYSQL_PASSWORD=phabricator
``` 

Here is the error messages I am getting 

```
ubuntu@phabricator:~/phabricator$ sudo docker-compose up
Creating phabricator_mysql_1
Creating phabricator_phabricator_1
Attaching to phabricator_mysql_1, phabricator_phabricator_1
mysql_1        | Initializing database
phabricator_1  | [ STARTING ] /etc/init.simple/10-boot-conf
phabricator_1  | + '[' -f /baked ']'
phabricator_1  | + '[' mysql '!=' '' ']'
phabricator_1  | + MYSQL_HOST_VARIABLE=mysql_PORT_3306_TCP_ADDR
phabricator_1  | + MYSQL_HOST=
phabricator_1  | + MYSQL_PORT_VARIABLE=mysql_PORT_3306_TCP_PORT
phabricator_1  | + MYSQL_PORT=
phabricator_1  | + unset MYSQL_HOST_VARIABLE
phabricator_1  | + unset MYSQL_PORT_VARIABLE
phabricator_1  | + '[' '' == '' ']'
phabricator_1  | + MYSQL_STORAGE_NAMESPACE=phabricator
phabricator_1  | + '[' letsencrypt == '' ']'
phabricator_1  | + '[' '' == '' ']'
phabricator_1  | + PHABRICATOR_VCS_USER=git
phabricator_1  | + '[' '' == '' ']'
phabricator_1  | + PHABRICATOR_STORAGE_TYPE=mysql
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' -f /config/script.pre ']'
phabricator_1  | + '[' -f /config/script.premig ']'
phabricator_1  | + '[' -f /config/script.post ']'
phabricator_1  | + '[' -f /config/script.phd ']'
phabricator_1  | + '[' -f /config/script.letsencrypt ']'
phabricator_1  | + '[' -f /config/letsencrypt.config ']'
phabricator_1  | + '[' -d /config/keycache ']'
phabricator_1  | + cat
phabricator_1  | + source /config.saved
phabricator_1  | ++ OVERRIDE_PHABRICATOR_URI=
phabricator_1  | ++ OVERRIDE_PHABRICATOR_BRANCH=
phabricator_1  | ++ OVERRIDE_ARCANIST_URI=
phabricator_1  | ++ OVERRIDE_ARCANIST_BRANCH=
phabricator_1  | ++ OVERRIDE_LIBPHUTIL_URI=
phabricator_1  | ++ OVERRIDE_LIBPHUTIL_BRANCH=
phabricator_1  | ++ PHABRICATOR_HOST=example.com
phabricator_1  | ++ PHABRICATOR_CDN=
phabricator_1  | ++ PHABRICATOR_REPOSITORY_PATH=/repos
phabricator_1  | ++ PHABRICATOR_STORAGE_TYPE=mysql
phabricator_1  | ++ PHABRICATOR_STORAGE_PATH=/filestore
phabricator_1  | ++ PHABRICATOR_STORAGE_BUCKET=
phabricator_1  | ++ PHABRICATOR_VCS_USER=git
phabricator_1  | ++ PHABRICATOR_VCS_PORT=
phabricator_1  | ++ PHABRICATOR_HOST_KEYS_PATH=/sshkeys
phabricator_1  | ++ AWS_S3_ACCESS_KEY=
phabricator_1  | ++ AWS_S3_SECRET_KEY=
phabricator_1  | ++ MYSQL_HOST=
phabricator_1  | ++ MYSQL_PORT=
phabricator_1  | ++ MYSQL_USER=
phabricator_1  | ++ MYSQL_PASS=
phabricator_1  | ++ MYSQL_STORAGE_NAMESPACE=phabricator
phabricator_1  | ++ ENABLE_APCU=
phabricator_1  | ++ ENABLE_UPDATE_ON_START=
phabricator_1  | ++ SSL_TYPE=letsencrypt
phabricator_1  | ++ SSL_CERTIFICATE=
phabricator_1  | ++ SSL_PRIVATE_KEY=
phabricator_1  | ++ SSL_EMAIL=''\''myemail'\'''
phabricator_1  | ++ SCRIPT_BEFORE_UPDATE=
phabricator_1  | ++ SCRIPT_BEFORE_MIGRATION=
phabricator_1  | ++ SCRIPT_AFTER_MIGRATION=
phabricator_1  | ++ SCRIPT_AFTER_LETS_ENCRYPT=
phabricator_1  | ++ SCRIPT_BEFORE_DAEMONS=
phabricator_1  | ++ SCRIPT_AFTER_DAEMONS=
phabricator_1  | + sed -i s/PHABRICATOR/git/g /etc/passwd
phabricator_1  | + sed s/__PHABRICATOR_VCS_USER__/git/g /etc/phabricator-ssh/sshd_config.phabricator.template
phabricator_1  | + sed s/__PHABRICATOR_VCS_USER__/git/g /etc/phabricator-ssh/phabricator-ssh-hook.sh.template
phabricator_1  | + sed s/__PHABRICATOR_VCS_USER__/git/g /etc/php5/fpm/php-fpm.conf.template
phabricator_1  | + chmod 755 /etc/phabricator-ssh/phabricator-ssh-hook.sh
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' == true ']'
phabricator_1  | + pushd /srv/phabricator/phabricator
phabricator_1  | /srv/phabricator/phabricator /
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' phabricator '!=' '' ']'
phabricator_1  | + sudo -u git ./bin/config set storage.default-namespace phabricator
phabricator_1  | Set 'storage.default-namespace' in local configuration.
phabricator_1  | + '[' example.com '!=' '' ']'
phabricator_1  | + '[' letsencrypt == none ']'
phabricator_1  | + sudo -u git ./bin/config set phabricator.base-uri example.com
phabricator_1  | Set 'phabricator.base-uri' in local configuration.
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + sudo -u git ./bin/config set phd.user git
phabricator_1  | Set 'phd.user' in local configuration.
phabricator_1  | + sudo -u git ./bin/config set pygments.enabled true
phabricator_1  | Set 'pygments.enabled' in local configuration.
phabricator_1  | + '[' /repos '!=' '' ']'
phabricator_1  | + sudo -u git ./bin/config set repository.default-local-path /repos
phabricator_1  | Set 'repository.default-local-path' in local configuration.
phabricator_1  | + '[' mysql == mysql ']'
phabricator_1  | + sudo -u git ./bin/config set storage.mysql-engine.max-size 67108864
mysql_1        | Database initialized
mysql_1        | MySQL init process in progress...
phabricator_1  | Set 'storage.mysql-engine.max-size' in local configuration.
phabricator_1  | + '[' mysql == disk ']'
phabricator_1  | + '[' mysql == s3 ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + '[' letsencrypt == none ']'
phabricator_1  | + APHLICT_PROTOCOL=https
phabricator_1  | + APHLICT_PORT=443
phabricator_1  | + sudo -u git ./bin/config set notification.servers '[{"type": "client","host": "example.com","port": 443,"protocol": "https","path": "/ws/"},{"type": "admin","host": "127.0.0.1","port": 22281,"protocol": "http"}]'
phabricator_1  | Set 'notification.servers' in local configuration.
phabricator_1  | + unset APHLICT_PROTOCOL
phabricator_1  | + unset APHLICT_PORT
phabricator_1  | + popd
phabricator_1  | /
phabricator_1  | + '[' '' == true ']'
phabricator_1  | + '[' '' '!=' '' ']'
phabricator_1  | + mysqlcheck --host= --port= --user= --password= --databases phabricator_search
phabricator_1  | mysqlcheck: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysql/mysql.sock' (2 "No such file or directory") when trying to connect
phabricator_1  | + true
phabricator_1  | + /srv/phabricator/phabricator/bin/storage upgrade --force
phabricator_1  | MySQL Credentials Not Configured
phabricator_1  |
phabricator_1  | Unable to connect to MySQL using the configured credentials. You must
phabricator_1  | configure standard credentials before you can upgrade storage. Run these
phabricator_1  | commands to set up credentials:
phabricator_1  |
phabricator_1  |   phabricator/ $ ./bin/config set mysql.host __host__
phabricator_1  |   phabricator/ $ ./bin/config set mysql.user __username__
phabricator_1  |   phabricator/ $ ./bin/config set mysql.pass __password__
phabricator_1  |
phabricator_1  | These standard credentials are separate from any administrative credentials
phabricator_1  | provided to this command with __--user__ or __--password__, and must be
phabricator_1  | configured correctly before you can proceed.
phabricator_1  |
phabricator_1  | Raw MySQL Error: Attempt to connect to root@localhost failed with error
phabricator_1  | #2002: No such file or directory.
phabricator_1  | [ FAILED ] /etc/init.simple/10-boot-conf
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/Factory' as time zone. Skipping it.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/posix/Factory' as time zone. Skipping it.
mysql_1        | Warning: Unable to load '/usr/share/zoneinfo/right/Factory' as time zone. Skipping it.
phabricator_phabricator_1 exited with code 1
```

**Comment by rswhiting** [comment]
It looks like you don't have `MYSQL_USER=phabricator` or `MYSQL_PASSWORD=phabricator` in the phabricator section of your config. Note this line in the output:
```
phabricator_1  | + mysqlcheck --host= --port= --user= --password= --databases phabricator_search
phabricator_1  | mysqlcheck: Got error: 2002: Can't connect to local MySQL server...
```

I think this case is still relevant though, because I'm getting the same error with this configuration:
```
version: '2'
services:
  phabricator:
    ports:
     - "62443:443"
     - "62080:80"
     - "62022:22"
    depends_on:
     - mysql
    links:
     - mysql
    environment:
     - MYSQL_LINKED_CONTAINER=mysql
     - MYSQL_USER=phabricator
     - MYSQL_PASS=phabricator
    image: hachque/phabricator
  mysql:
    volumes:
     - /mnt/docker/phabricator/mysql:/var/lib/mysql
    image: mysql:5.7.16
    environment:
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
     - MYSQL_USER=phabricator
     - MYSQL_PASSWORD=phabricator
```
with this error
```
phabricator_1  | + mysqlcheck --host= --port= --user=phabricator --password=phabricator --databases phabricator_search
phabricator_1  | mysqlcheck: Got error: 2002: Can't connect to local MySQL server 
```

It looks like the `MYSQL_LINKED_CONTAINER` isn't functioning as expected.
