### ISSUE TITLE
Unable to establish a connection to any database host

### ISSUE THREAD

**Issue by majuansari** [hach-que-docker/phabricator#57]
I am getting the following error

> [2016-11-23 07:19:51] EXCEPTION: (PhabricatorClusterStrandedException) Unable to establish a connection to any database host (while trying "phabricator_config"). All masters and replicas are completely unreachable. at [<phabricator>/src/infrastructure/storage/lisk/PhabricatorLiskDAO.php:140]

Below is the composer part
```
    phabricator:
        ports:
             - "62443:443"
             - "62080:80"
             - "62022:22"
        volumes:
             - ./data/phabricator/repos:/repos
             - ./data/phabricator/extensions:/srv/phabricator/phabricator/src/extensions
        depends_on:
            - mysql
        links:
            - mysql
        environment:
             - MYSQL_LINKED_CONTAINER=MYSQL
             - MYSQL_USER=maju
             - MYSQL_PASS=1234maju
             - PHABRICATOR_REPOSITORY_PATH=/repos
             - PHABRICATOR_HOST=phab.dev
        image: hachque/phabricator
```

Can any one help please
